baseurl      = "https://chartexample.com"
title        = "chartexample"
languageCode = "en-us"
theme        = "chart-example-theme"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  EnableThemeToggle = true

  customCSS = ["/style.css"]
  customJS = ["https://d3js.org/d3.v7.min.js", "https://unpkg.com/pixi.js@7.x/dist/pixi.min.js"]

  # Subtitle for home
  homeSubtitle = "Blog about creating charts and data visualizations"

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Blog about creating charts and data visualizations"
  keywords = "chart, blog, d3, chart.js, examples"
  images = [""]

[permalinks]
  posts = "/posts/:year/:month/:title/"
    
[languages]
  [languages.en]
    title = "chartexample.com"
    subtitle = "Blog about creating charts and data visualizations"
    keywords = "chartexample.com, blog, charts, d3, visualizations, plots"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "chartexample.com"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "chartexample.com"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "charts"
    name       = "Charts"
    url        = "/charts"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "blog/"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

[author]
  name = "Alex Chirkin"

[[params.social]]
  name = "github"
  url = "https://github.com/b0000ring"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/achirkin/"

  

[params.footer]
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    ]